export type {
  BomAssemblyProjection,
  BomAssemblyQuantityFacts,
  BomItemDeleteResult,
  BomItemDocumentDeleteInput,
  BomItemDocumentMetadata,
  BomItemDocumentPayload,
  BomItemDocumentUploadInput,
  BomItemExtractedValues,
  BomItemExtractionInput,
  BomItemExtractionResult,
  BomItemExtractionSource,
  BomItemAppliedFilters,
  BomItemFilterOptions,
  BomItemInput,
  BomItemListInput,
  BomItemListResult,
  BomItemListRow,
  BomItemPickerInput,
  BomItemPickerResult,
  BomItemDetail,
  BomItemExistingImageInput,
  BomItemImageInput,
  BomItemImageMetadata,
  BomItemImagePayload,
  BomItemImageSummary,
  BomItemImageWriteInput,
  BomItemNewImageInput,
  BomItemFormOptions,
  BomItemOption,
  BomItemOptionInput,
  BomItemStatus,
  BomItemSummary,
  BomItemUpdateInput,
  BomItemUsage,
  BomGenerationItem,
  BomGenerationTemplate,
  BomGenerationTemplateLine,
  BomQuantityRule,
  BomQuantityStatus,
  BomTemplateLineInput,
  ConsolidatedBomLine,
  GeneratedBomAssembly,
  GeneratedBomLine,
  GeneratedBomWarning,
  GeneratedBomWarningCode,
  GeneratedDrawingBom,
  SaveSymbolBomTemplateInput,
  SymbolBomEditorData,
  SymbolBomTemplateDetail,
  SymbolBomTemplateLineDetail
} from "../data/schema";

export type ActionResult<T> =
  | { ok: true; data: T }
  | { ok: false; error: string };
