import { createLargePanelPerformanceSource } from "../../src/features/drawing_panel_wiring/tests/release-fixtures";
import { panelWiringSourcePackageSchema } from "../../src/features/drawing_panel_wiring/data/schema";
import { buildPackageConnectivityGraphFromValidatedSource } from "../../src/features/drawing_panel_wiring/logic/services/connectivity-graph";
import { buildElectricalNetworkIndex } from "../../src/features/drawing_panel_wiring/logic/services/electrical-network-index";
import { buildPanelEngineeringSnapshot } from "../../src/features/drawing_panel_wiring/logic/services/panel-engineering-snapshot";
import { buildPlacementWireContextDisplayIndex } from "../../src/features/drawing_panel_wiring/logic/services/placement-wire-context";
import { createPanelWiringSource } from "../../src/features/drawing_canvas/api/panel-wiring-contracts";
import { collectPlacementWireContextRequests, buildPlacementConnectionDisplayModeIndex } from "../../src/features/drawing_canvas/logic/services/drawing-placement-connection-display";
import { buildConnectedWireScheduleIndex, isConnectedWireScheduleAnnotation } from "../../src/features/drawing_connected_wire_schedule/api/public";
import { parseDrawingModelJson, stringifyDrawingModel } from "../../src/features/drawing_canvas/data/schema";
import { renderDrawingToSvg } from "../../src/features/drawing_canvas/logic/services/drawing-svg-renderer";
import { toSheetCanvasModel } from "../../src/features/drawing_canvas/logic/commands/drawing-sheet-commands";
import { reconcileDrawingAssets } from "../../src/features/drawing_asset_manager/logic/use_cases/drawing-asset-manager-use-cases";
import { auditSymbol, denseModel, mixedModel, validateFixture } from "./fixtures";
import { guard, measure, write, freshMetricFile } from "./common";
guard();
const metricFile=freshMetricFile("cpu-metrics");
const results:ReturnType<typeof measure>[]=[];
const add=(name:string,operation:()=>unknown)=>{const metric=measure(name,operation);results.push(metric);console.log(JSON.stringify({...metric,samplesMs:undefined}));write(metricFile,results);};
const large=createLargePanelPerformanceSource();
const graph=buildPackageConnectivityGraphFromValidatedSource(large);
write("source-only-fixture.json",{sha256:(await import("./common")).sha(JSON.stringify(large)),sheets:large.sheets.length,assets:large.assets.length,occurrences:large.sheets.reduce((n,s)=>n+s.occurrences.length,0),connections:large.sheets.reduce((n,s)=>n+s.connections.length,0),terminals:graph.terminalsById.size,internalWires:graph.internalWiresById.size});
add("source120.validation-and-graph",()=>buildPanelEngineeringSnapshot(large,"audit"));
add("source120.validation",()=>panelWiringSourcePackageSchema.parse(large));
add("source120.graph.validated",()=>buildPackageConnectivityGraphFromValidatedSource(large));
add("source120.electrical-network",()=>buildElectricalNetworkIndex(graph));
const requests=large.sheets.flatMap(s=>s.panelDrawingContext?s.occurrences.map(o=>({sheetId:s.id,placementId:o.placementId,mode:"all_connected" as const})):[]);
add("source120.connection-display",()=>buildPlacementWireContextDisplayIndex({graph,requests}));
const symbols=Array.from({length:25},(_,i)=>auditSymbol(i));
for(const [name,model] of [["mixed10",mixedModel(10)],["mixed40",mixedModel(40)],["mixed120",mixedModel(120)],["dense",denseModel()]] as const){
  const facts=validateFixture(model);const json=stringifyDrawingModel(model);
  const source=createPanelWiringSource(model,symbols);
  const graph=buildPackageConnectivityGraphFromValidatedSource(source);
  const requests=collectPlacementWireContextRequests(model);
  const schedules=new Map(model.sheets.map(s=>[s.id,s.annotations.filter(isConnectedWireScheduleAnnotation)]));
  const display=buildPlacementConnectionDisplayModeIndex(model);
  console.log(JSON.stringify({fixture:name,...facts}));
  add(name+".json.parse-normalize",()=>parseDrawingModelJson(json));
  add(name+".json.stringify-normalize",()=>stringifyDrawingModel(model));
  add(name+".assets.reconcile",()=>reconcileDrawingAssets(model,symbols));
  add(name+".source.adapter",()=>createPanelWiringSource(model,symbols));
  add(name+".graph.validated",()=>buildPackageConnectivityGraphFromValidatedSource(source));
  add(name+".connection-display",()=>buildPlacementWireContextDisplayIndex({graph,requests}));
  add(name+".schedule-projection",()=>buildConnectedWireScheduleIndex({graph,schedulesBySheetId:schedules,displayModesBySheetPlacement:display}));
  const sheet=toSheetCanvasModel(model,model.sheets[0].id);
  add(name+".active-svg",()=>renderDrawingToSvg({model:sheet,approvedSymbols:symbols,assets:model.assets,showConnections:true,showAnchors:false,sheetNumber:1,sheetCount:model.sheets.length,drawingTitle:"Synthetic audit"}));
}
